### ISSUE TITLE
🐛 找不到或无法加载主类 com.codyi.xml2axml.test.Main

### ISSUE THREAD

**Issue by ckbkdj** [codyi96/xml2axml#1]
回编译失败 报资源错误

**Comment by codyi96** [comment]
基于以下工程二次开发：
- [xml2axml](https://github.com/l741589/xml2axml) by [l741589](https://github.com/l741589)
- [xml2axml](https://github.com/hzw1199/xml2axml) by [hzw1199](https://github.com/hzw1199)

改动说明见[releases](https://github.com/codyi96/xml2axml/releases)

---

使用中发现不少Bug，持续修正中...

有具体问题请贴Log交流 : D

**Comment by ckbkdj** [comment]
错误: 找不到或无法加载主类 com.codyi.xml2axml.test.Main
发布的版本...没做好

**Comment by codyi96** [comment]
嗯，今晚发一个新版本，使用临时方案修复一些问题。后续会有个重构版

**Comment by ckbkdj** [comment]
java.io.EOFException
        at android.content.res.IntReader.readInt(IntReader.java:97)
        at android.content.res.IntReader.readInt(IntReader.java:75)
        at android.content.res.ChunkUtil.readCheckType(ChunkUtil.java:27)
        at android.content.res.AXmlResourceParser.doNext(AXmlResourceParser.java:769)
        at android.content.res.AXmlResourceParser.next(AXmlResourceParser.java:73)
        at com.codyi.xml2axml.test.AXMLPrinter.decode(AXMLPrinter.java:61)
        at com.codyi.xml2axml.test.AXMLPrinter.main(AXMLPrinter.java:46)
        at com.codyi.xml2axml.test.Main.decode(Main.java:37)
        at com.codyi.xml2axml.test.Main.main(Main.java:21)
这是第二个,我修改里面的编译报错

**Comment by codyi96** [comment]
Fixed. see [v2.0.0](https://github.com/codyi96/xml2axml/releases/tag/2.0.0)
