### ISSUE TITLE
🐛 当前报错 String: '' not found 

### ISSUE THREAD

**Issue by ckbkdj** [codyi96/xml2axml#3]
Exception in thread "main" java.lang.RuntimeException: String: '' not found
        at com.codyi.xml2axml.chunks.StringPoolChunk.stringIndex(StringPoolChunk.java:225)
        at com.codyi.xml2axml.chunks.Chunk.stringIndex(Chunk.java:126)
        at com.codyi.xml2axml.chunks.StartTagChunk.writeEx(StartTagChunk.java:81)
        at com.codyi.xml2axml.chunks.Chunk.write(Chunk.java:98)
        at com.codyi.xml2axml.chunks.TagChunk.writeEx(TagChunk.java:55)
        at com.codyi.xml2axml.chunks.Chunk.write(Chunk.java:98)
        at com.codyi.xml2axml.chunks.XmlChunk.writeEx(XmlChunk.java:46)
        at com.codyi.xml2axml.chunks.Chunk.write(Chunk.java:98)
        at com.codyi.xml2axml.Encoder.encode(Encoder.java:84)
        at com.codyi.xml2axml.Encoder.encodeFile(Encoder.java:32)
        at com.codyi.xml2axml.test.Main.encode(Main.java:31)
        at com.codyi.xml2axml.test.Main.main(Main.java:19)

**Comment by ckbkdj** [comment]
[xml2axml.zip](https://github.com/codyi96/xml2axml/files/4697391/xml2axml.zip)
样本数据

**Comment by codyi96** [comment]
Fixed. see [v2.0.1](https://github.com/codyi96/xml2axml/releases/tag/2.0.1)
