### ISSUE TITLE
🐛[BUG] ...ndex 4296 out of bounds for length 4296

### ISSUE THREAD

**Issue by yinli155** [codyi96/xml2axml#9]
java.lang.ArrayIndexOutOfBoundsException: Index 4296 out of bounds for length 4296
        at android.content.res.StringBlock.getShort(StringBlock.java:231)
        at android.content.res.StringBlock.getString(StringBlock.java:91)
        at android.content.res.AXmlResourceParser.getNamespacePrefix(AXmlResourceParser.java:182)
        at com.codyi.xml2axml.test.AXMLPrinter.decode(AXMLPrinter.java:82)
        at com.codyi.xml2axml.test.AXMLPrinter.main(AXMLPrinter.java:46)
        at com.codyi.xml2axml.test.Main.decode(Main.java:37)
        at com.codyi.xml2axml.test.Main.main(Main.java:21)

**Comment by bigConifer** [comment]
@yinli155 @codyi96 
It looks like [this](https://github.com/hzw1199/xml2axml/issues/5) long known bug in the AXMLPrinter2 component of xml2axml. It's already fixed [here](https://github.com/bigConifer/xml2axml/commit/2c2af082690edbe219b22ee48f9af849bed70b49).
